// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "SearchIndex.h"
#import "CorrectedQuery.h"

@implementation SearchIndex

@synthesize indexName = _indexName;
@synthesize results = _results;
@synthesize pages = _pages;
@synthesize correctedQuery = _correctedQuery;
@synthesize relevanceRank = _relevanceRank;
@synthesize asin = _asin;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IndexName" propertyName:@"indexName" type:PICO_TYPE_STRING clazz:nil];
    map[@"indexName"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Results" propertyName:@"results" type:PICO_TYPE_LONG clazz:nil];
    map[@"results"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Pages" propertyName:@"pages" type:PICO_TYPE_LONG clazz:nil];
    map[@"pages"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CorrectedQuery" propertyName:@"correctedQuery" type:PICO_TYPE_OBJECT clazz:[CorrectedQuery class]];
    map[@"correctedQuery"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RelevanceRank" propertyName:@"relevanceRank" type:PICO_TYPE_LONG clazz:nil];
    map[@"relevanceRank"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"ASIN" propertyName:@"asin" type:PICO_TYPE_STRING clazz:nil];
    map[@"asin"] = ps;
    
    return map;
}




@end
