// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "ItemSearchRequest.h"

@implementation ItemSearchRequest

@synthesize actor = _actor;
@synthesize artist = _artist;
@synthesize availability = _availability;
@synthesize audienceRating = _audienceRating;
@synthesize author = _author;
@synthesize brand = _brand;
@synthesize browseNode = _browseNode;
@synthesize composer = _composer;
@synthesize condition = _condition;
@synthesize conductor = _conductor;
@synthesize director = _director;
@synthesize itemPage = _itemPage;
@synthesize keywords = _keywords;
@synthesize manufacturer = _manufacturer;
@synthesize maximumPrice = _maximumPrice;
@synthesize merchantId = _merchantId;
@synthesize minimumPrice = _minimumPrice;
@synthesize minPercentageOff = _minPercentageOff;
@synthesize musicLabel = _musicLabel;
@synthesize orchestra = _orchestra;
@synthesize power = _power;
@synthesize publisher = _publisher;
@synthesize relatedItemPage = _relatedItemPage;
@synthesize relationshipType = _relationshipType;
@synthesize responseGroup = _responseGroup;
@synthesize searchIndex = _searchIndex;
@synthesize sort = _sort;
@synthesize title = _title;
@synthesize releaseDate = _releaseDate;
@synthesize includeReviewsSummary = _includeReviewsSummary;
@synthesize truncateReviewsAt = _truncateReviewsAt;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Actor" propertyName:@"actor" type:PICO_TYPE_STRING clazz:nil];
    map[@"actor"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Artist" propertyName:@"artist" type:PICO_TYPE_STRING clazz:nil];
    map[@"artist"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Availability" propertyName:@"availability" type:PICO_TYPE_STRING clazz:nil];
    map[@"availability"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"AudienceRating" propertyName:@"audienceRating" type:PICO_TYPE_STRING clazz:nil];
    map[@"audienceRating"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Author" propertyName:@"author" type:PICO_TYPE_STRING clazz:nil];
    map[@"author"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Brand" propertyName:@"brand" type:PICO_TYPE_STRING clazz:nil];
    map[@"brand"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"BrowseNode" propertyName:@"browseNode" type:PICO_TYPE_STRING clazz:nil];
    map[@"browseNode"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Composer" propertyName:@"composer" type:PICO_TYPE_STRING clazz:nil];
    map[@"composer"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Condition" propertyName:@"condition" type:PICO_TYPE_STRING clazz:nil];
    map[@"condition"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Conductor" propertyName:@"conductor" type:PICO_TYPE_STRING clazz:nil];
    map[@"conductor"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Director" propertyName:@"director" type:PICO_TYPE_STRING clazz:nil];
    map[@"director"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ItemPage" propertyName:@"itemPage" type:PICO_TYPE_LONG clazz:nil];
    map[@"itemPage"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Keywords" propertyName:@"keywords" type:PICO_TYPE_STRING clazz:nil];
    map[@"keywords"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Manufacturer" propertyName:@"manufacturer" type:PICO_TYPE_STRING clazz:nil];
    map[@"manufacturer"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MaximumPrice" propertyName:@"maximumPrice" type:PICO_TYPE_LONG clazz:nil];
    map[@"maximumPrice"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MerchantId" propertyName:@"merchantId" type:PICO_TYPE_STRING clazz:nil];
    map[@"merchantId"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MinimumPrice" propertyName:@"minimumPrice" type:PICO_TYPE_LONG clazz:nil];
    map[@"minimumPrice"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MinPercentageOff" propertyName:@"minPercentageOff" type:PICO_TYPE_LONG clazz:nil];
    map[@"minPercentageOff"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MusicLabel" propertyName:@"musicLabel" type:PICO_TYPE_STRING clazz:nil];
    map[@"musicLabel"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Orchestra" propertyName:@"orchestra" type:PICO_TYPE_STRING clazz:nil];
    map[@"orchestra"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Power" propertyName:@"power" type:PICO_TYPE_STRING clazz:nil];
    map[@"power"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Publisher" propertyName:@"publisher" type:PICO_TYPE_STRING clazz:nil];
    map[@"publisher"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RelatedItemPage" propertyName:@"relatedItemPage" type:PICO_TYPE_STRING clazz:nil];
    map[@"relatedItemPage"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"RelationshipType" propertyName:@"relationshipType" type:PICO_TYPE_STRING clazz:nil];
    map[@"relationshipType"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"ResponseGroup" propertyName:@"responseGroup" type:PICO_TYPE_STRING clazz:nil];
    map[@"responseGroup"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SearchIndex" propertyName:@"searchIndex" type:PICO_TYPE_STRING clazz:nil];
    map[@"searchIndex"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Sort" propertyName:@"sort" type:PICO_TYPE_STRING clazz:nil];
    map[@"sort"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Title" propertyName:@"title" type:PICO_TYPE_STRING clazz:nil];
    map[@"title"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ReleaseDate" propertyName:@"releaseDate" type:PICO_TYPE_STRING clazz:nil];
    map[@"releaseDate"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IncludeReviewsSummary" propertyName:@"includeReviewsSummary" type:PICO_TYPE_STRING clazz:nil];
    map[@"includeReviewsSummary"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TruncateReviewsAt" propertyName:@"truncateReviewsAt" type:PICO_TYPE_LONG clazz:nil];
    map[@"truncateReviewsAt"] = ps;
    
    return map;
}




@end
