// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "ItemLookupRequest.h"

@implementation ItemLookupRequest

@synthesize condition = _condition;
@synthesize idType = _idType;
@synthesize merchantId = _merchantId;
@synthesize itemId = _itemId;
@synthesize responseGroup = _responseGroup;
@synthesize searchIndex = _searchIndex;
@synthesize variationPage = _variationPage;
@synthesize relatedItemPage = _relatedItemPage;
@synthesize relationshipType = _relationshipType;
@synthesize includeReviewsSummary = _includeReviewsSummary;
@synthesize truncateReviewsAt = _truncateReviewsAt;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Condition" propertyName:@"condition" type:PICO_TYPE_STRING clazz:nil];
    map[@"condition"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IdType" propertyName:@"idType" type:PICO_TYPE_STRING clazz:nil];
    map[@"idType"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MerchantId" propertyName:@"merchantId" type:PICO_TYPE_STRING clazz:nil];
    map[@"merchantId"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"ItemId" propertyName:@"itemId" type:PICO_TYPE_STRING clazz:nil];
    map[@"itemId"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"ResponseGroup" propertyName:@"responseGroup" type:PICO_TYPE_STRING clazz:nil];
    map[@"responseGroup"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SearchIndex" propertyName:@"searchIndex" type:PICO_TYPE_STRING clazz:nil];
    map[@"searchIndex"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"VariationPage" propertyName:@"variationPage" type:PICO_TYPE_STRING clazz:nil];
    map[@"variationPage"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RelatedItemPage" propertyName:@"relatedItemPage" type:PICO_TYPE_STRING clazz:nil];
    map[@"relatedItemPage"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"RelationshipType" propertyName:@"relationshipType" type:PICO_TYPE_STRING clazz:nil];
    map[@"relationshipType"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IncludeReviewsSummary" propertyName:@"includeReviewsSummary" type:PICO_TYPE_STRING clazz:nil];
    map[@"includeReviewsSummary"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TruncateReviewsAt" propertyName:@"truncateReviewsAt" type:PICO_TYPE_LONG clazz:nil];
    map[@"truncateReviewsAt"] = ps;
    
    return map;
}




@end
