// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "ItemAttributes.h"
#import "UPCList.h"
#import "NonNegativeIntegerWithUnits.h"
#import "DecimalWithUnits.h"
#import "PackageDimensions.h"
#import "EANList.h"
#import "Creator.h"
#import "Price.h"
#import "ItemDimensions.h"
#import "CatalogNumberList.h"
#import "Languages.h"

@implementation ItemAttributes

@synthesize actor = _actor;
@synthesize artist = _artist;
@synthesize aspectRatio = _aspectRatio;
@synthesize audienceRating = _audienceRating;
@synthesize audioFormat = _audioFormat;
@synthesize author = _author;
@synthesize binding = _binding;
@synthesize brand = _brand;
@synthesize catalogNumberList = _catalogNumberList;
@synthesize category = _category;
@synthesize ceroAgeRating = _ceroAgeRating;
@synthesize clothingSize = _clothingSize;
@synthesize color = _color;
@synthesize creator = _creator;
@synthesize department = _department;
@synthesize director = _director;
@synthesize ean = _ean;
@synthesize eanList = _eanList;
@synthesize edition = _edition;
@synthesize eisbn = _eisbn;
@synthesize episodeSequence = _episodeSequence;
@synthesize esrbAgeRating = _esrbAgeRating;
@synthesize feature = _feature;
@synthesize format = _format;
@synthesize genre = _genre;
@synthesize hardwarePlatform = _hardwarePlatform;
@synthesize hazardousMaterialType = _hazardousMaterialType;
@synthesize isAdultProduct = _isAdultProduct;
@synthesize isAutographed = _isAutographed;
@synthesize isbn = _isbn;
@synthesize isEligibleForTradeIn = _isEligibleForTradeIn;
@synthesize isMemorabilia = _isMemorabilia;
@synthesize issuesPerYear = _issuesPerYear;
@synthesize itemDimensions = _itemDimensions;
@synthesize itemPartNumber = _itemPartNumber;
@synthesize label = _label;
@synthesize languages = _languages;
@synthesize legalDisclaimer = _legalDisclaimer;
@synthesize listPrice = _listPrice;
@synthesize magazineType = _magazineType;
@synthesize manufacturer = _manufacturer;
@synthesize manufacturerMaximumAge = _manufacturerMaximumAge;
@synthesize manufacturerMinimumAge = _manufacturerMinimumAge;
@synthesize manufacturerPartsWarrantyDescription = _manufacturerPartsWarrantyDescription;
@synthesize mediaType = _mediaType;
@synthesize model = _model;
@synthesize modelYear = _modelYear;
@synthesize mpn = _mpn;
@synthesize numberOfDiscs = _numberOfDiscs;
@synthesize numberOfIssues = _numberOfIssues;
@synthesize numberOfItems = _numberOfItems;
@synthesize numberOfPages = _numberOfPages;
@synthesize numberOfTracks = _numberOfTracks;
@synthesize operatingSystem = _operatingSystem;
@synthesize packageDimensions = _packageDimensions;
@synthesize packageQuantity = _packageQuantity;
@synthesize partNumber = _partNumber;
@synthesize pictureFormat = _pictureFormat;
@synthesize platform = _platform;
@synthesize productGroup = _productGroup;
@synthesize productTypeName = _productTypeName;
@synthesize productTypeSubcategory = _productTypeSubcategory;
@synthesize publicationDate = _publicationDate;
@synthesize publisher = _publisher;
@synthesize regionCode = _regionCode;
@synthesize releaseDate = _releaseDate;
@synthesize runningTime = _runningTime;
@synthesize seikodoProductCode = _seikodoProductCode;
@synthesize size = _size;
@synthesize sku = _sku;
@synthesize studio = _studio;
@synthesize subscriptionLength = _subscriptionLength;
@synthesize title = _title;
@synthesize trackSequence = _trackSequence;
@synthesize tradeInValue = _tradeInValue;
@synthesize upc = _upc;
@synthesize upcList = _upcList;
@synthesize warranty = _warranty;
@synthesize weeeTaxValue = _weeeTaxValue;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"ItemAttributes" nsUri:@"http://webservices.amazon.com/AWSECommerceService/2011-08-01"];
    //[cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Actor" propertyName:@"actor" type:PICO_TYPE_STRING clazz:nil];
    map[@"actor"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Artist" propertyName:@"artist" type:PICO_TYPE_STRING clazz:nil];
    map[@"artist"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"AspectRatio" propertyName:@"aspectRatio" type:PICO_TYPE_STRING clazz:nil];
    map[@"aspectRatio"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"AudienceRating" propertyName:@"audienceRating" type:PICO_TYPE_STRING clazz:nil];
    map[@"audienceRating"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"AudioFormat" propertyName:@"audioFormat" type:PICO_TYPE_STRING clazz:nil];
    map[@"audioFormat"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Author" propertyName:@"author" type:PICO_TYPE_STRING clazz:nil];
    map[@"author"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Binding" propertyName:@"binding" type:PICO_TYPE_STRING clazz:nil];
    map[@"binding"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Brand" propertyName:@"brand" type:PICO_TYPE_STRING clazz:nil];
    map[@"brand"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CatalogNumberList" propertyName:@"catalogNumberList" type:PICO_TYPE_OBJECT clazz:[CatalogNumberList class]];
    map[@"catalogNumberList"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Category" propertyName:@"category" type:PICO_TYPE_STRING clazz:nil];
    map[@"category"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CEROAgeRating" propertyName:@"ceroAgeRating" type:PICO_TYPE_STRING clazz:nil];
    map[@"ceroAgeRating"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ClothingSize" propertyName:@"clothingSize" type:PICO_TYPE_STRING clazz:nil];
    map[@"clothingSize"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Color" propertyName:@"color" type:PICO_TYPE_STRING clazz:nil];
    map[@"color"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Creator" propertyName:@"creator" type:PICO_TYPE_OBJECT clazz:[Creator class]];
    map[@"creator"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Department" propertyName:@"department" type:PICO_TYPE_STRING clazz:nil];
    map[@"department"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Director" propertyName:@"director" type:PICO_TYPE_STRING clazz:nil];
    map[@"director"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"EAN" propertyName:@"ean" type:PICO_TYPE_STRING clazz:nil];
    map[@"ean"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"EANList" propertyName:@"eanList" type:PICO_TYPE_OBJECT clazz:[EANList class]];
    map[@"eanList"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Edition" propertyName:@"edition" type:PICO_TYPE_STRING clazz:nil];
    map[@"edition"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"EISBN" propertyName:@"eisbn" type:PICO_TYPE_STRING clazz:nil];
    map[@"eisbn"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"EpisodeSequence" propertyName:@"episodeSequence" type:PICO_TYPE_STRING clazz:nil];
    map[@"episodeSequence"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ESRBAgeRating" propertyName:@"esrbAgeRating" type:PICO_TYPE_STRING clazz:nil];
    map[@"esrbAgeRating"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Feature" propertyName:@"feature" type:PICO_TYPE_STRING clazz:nil];
    map[@"feature"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Format" propertyName:@"format" type:PICO_TYPE_STRING clazz:nil];
    map[@"format"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Genre" propertyName:@"genre" type:PICO_TYPE_STRING clazz:nil];
    map[@"genre"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"HardwarePlatform" propertyName:@"hardwarePlatform" type:PICO_TYPE_STRING clazz:nil];
    map[@"hardwarePlatform"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"HazardousMaterialType" propertyName:@"hazardousMaterialType" type:PICO_TYPE_STRING clazz:nil];
    map[@"hazardousMaterialType"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IsAdultProduct" propertyName:@"isAdultProduct" type:PICO_TYPE_BOOL clazz:nil];
    map[@"isAdultProduct"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IsAutographed" propertyName:@"isAutographed" type:PICO_TYPE_BOOL clazz:nil];
    map[@"isAutographed"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ISBN" propertyName:@"isbn" type:PICO_TYPE_STRING clazz:nil];
    map[@"isbn"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IsEligibleForTradeIn" propertyName:@"isEligibleForTradeIn" type:PICO_TYPE_BOOL clazz:nil];
    map[@"isEligibleForTradeIn"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IsMemorabilia" propertyName:@"isMemorabilia" type:PICO_TYPE_BOOL clazz:nil];
    map[@"isMemorabilia"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IssuesPerYear" propertyName:@"issuesPerYear" type:PICO_TYPE_STRING clazz:nil];
    map[@"issuesPerYear"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ItemDimensions" propertyName:@"itemDimensions" type:PICO_TYPE_OBJECT clazz:[ItemDimensions class]];
    map[@"itemDimensions"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ItemPartNumber" propertyName:@"itemPartNumber" type:PICO_TYPE_STRING clazz:nil];
    map[@"itemPartNumber"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Label" propertyName:@"label" type:PICO_TYPE_STRING clazz:nil];
    map[@"label"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Languages" propertyName:@"languages" type:PICO_TYPE_OBJECT clazz:[Languages class]];
    map[@"languages"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"LegalDisclaimer" propertyName:@"legalDisclaimer" type:PICO_TYPE_STRING clazz:nil];
    map[@"legalDisclaimer"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ListPrice" propertyName:@"listPrice" type:PICO_TYPE_OBJECT clazz:[Price class]];
    map[@"listPrice"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MagazineType" propertyName:@"magazineType" type:PICO_TYPE_STRING clazz:nil];
    map[@"magazineType"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Manufacturer" propertyName:@"manufacturer" type:PICO_TYPE_STRING clazz:nil];
    map[@"manufacturer"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ManufacturerMaximumAge" propertyName:@"manufacturerMaximumAge" type:PICO_TYPE_OBJECT clazz:[DecimalWithUnits class]];
    map[@"manufacturerMaximumAge"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ManufacturerMinimumAge" propertyName:@"manufacturerMinimumAge" type:PICO_TYPE_OBJECT clazz:[DecimalWithUnits class]];
    map[@"manufacturerMinimumAge"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ManufacturerPartsWarrantyDescription" propertyName:@"manufacturerPartsWarrantyDescription" type:PICO_TYPE_STRING clazz:nil];
    map[@"manufacturerPartsWarrantyDescription"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MediaType" propertyName:@"mediaType" type:PICO_TYPE_STRING clazz:nil];
    map[@"mediaType"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Model" propertyName:@"model" type:PICO_TYPE_STRING clazz:nil];
    map[@"model"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ModelYear" propertyName:@"modelYear" type:PICO_TYPE_LONG clazz:nil];
    map[@"modelYear"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MPN" propertyName:@"mpn" type:PICO_TYPE_STRING clazz:nil];
    map[@"mpn"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"NumberOfDiscs" propertyName:@"numberOfDiscs" type:PICO_TYPE_LONG clazz:nil];
    map[@"numberOfDiscs"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"NumberOfIssues" propertyName:@"numberOfIssues" type:PICO_TYPE_LONG clazz:nil];
    map[@"numberOfIssues"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"NumberOfItems" propertyName:@"numberOfItems" type:PICO_TYPE_LONG clazz:nil];
    map[@"numberOfItems"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"NumberOfPages" propertyName:@"numberOfPages" type:PICO_TYPE_LONG clazz:nil];
    map[@"numberOfPages"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"NumberOfTracks" propertyName:@"numberOfTracks" type:PICO_TYPE_LONG clazz:nil];
    map[@"numberOfTracks"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"OperatingSystem" propertyName:@"operatingSystem" type:PICO_TYPE_STRING clazz:nil];
    map[@"operatingSystem"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"PackageDimensions" propertyName:@"packageDimensions" type:PICO_TYPE_OBJECT clazz:[PackageDimensions class]];
    map[@"packageDimensions"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"PackageQuantity" propertyName:@"packageQuantity" type:PICO_TYPE_LONG clazz:nil];
    map[@"packageQuantity"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"PartNumber" propertyName:@"partNumber" type:PICO_TYPE_STRING clazz:nil];
    map[@"partNumber"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"PictureFormat" propertyName:@"pictureFormat" type:PICO_TYPE_STRING clazz:nil];
    map[@"pictureFormat"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Platform" propertyName:@"platform" type:PICO_TYPE_STRING clazz:nil];
    map[@"platform"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ProductGroup" propertyName:@"productGroup" type:PICO_TYPE_STRING clazz:nil];
    map[@"productGroup"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ProductTypeName" propertyName:@"productTypeName" type:PICO_TYPE_STRING clazz:nil];
    map[@"productTypeName"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ProductTypeSubcategory" propertyName:@"productTypeSubcategory" type:PICO_TYPE_STRING clazz:nil];
    map[@"productTypeSubcategory"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"PublicationDate" propertyName:@"publicationDate" type:PICO_TYPE_STRING clazz:nil];
    map[@"publicationDate"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Publisher" propertyName:@"publisher" type:PICO_TYPE_STRING clazz:nil];
    map[@"publisher"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RegionCode" propertyName:@"regionCode" type:PICO_TYPE_STRING clazz:nil];
    map[@"regionCode"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ReleaseDate" propertyName:@"releaseDate" type:PICO_TYPE_STRING clazz:nil];
    map[@"releaseDate"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RunningTime" propertyName:@"runningTime" type:PICO_TYPE_OBJECT clazz:[DecimalWithUnits class]];
    map[@"runningTime"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SeikodoProductCode" propertyName:@"seikodoProductCode" type:PICO_TYPE_STRING clazz:nil];
    map[@"seikodoProductCode"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Size" propertyName:@"size" type:PICO_TYPE_STRING clazz:nil];
    map[@"size"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SKU" propertyName:@"sku" type:PICO_TYPE_STRING clazz:nil];
    map[@"sku"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Studio" propertyName:@"studio" type:PICO_TYPE_STRING clazz:nil];
    map[@"studio"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SubscriptionLength" propertyName:@"subscriptionLength" type:PICO_TYPE_OBJECT clazz:[NonNegativeIntegerWithUnits class]];
    map[@"subscriptionLength"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Title" propertyName:@"title" type:PICO_TYPE_STRING clazz:nil];
    map[@"title"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TrackSequence" propertyName:@"trackSequence" type:PICO_TYPE_STRING clazz:nil];
    map[@"trackSequence"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TradeInValue" propertyName:@"tradeInValue" type:PICO_TYPE_OBJECT clazz:[Price class]];
    map[@"tradeInValue"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UPC" propertyName:@"upc" type:PICO_TYPE_STRING clazz:nil];
    map[@"upc"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UPCList" propertyName:@"upcList" type:PICO_TYPE_OBJECT clazz:[UPCList class]];
    map[@"upcList"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Warranty" propertyName:@"warranty" type:PICO_TYPE_STRING clazz:nil];
    map[@"warranty"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"WEEETaxValue" propertyName:@"weeeTaxValue" type:PICO_TYPE_OBJECT clazz:[Price class]];
    map[@"weeeTaxValue"] = ps;
    
    return map;
}




@end
