// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OfferListing.h"
#import "AvailabilityAttributes.h"
#import "Price.h"

@implementation OfferListing

@synthesize offerListingId = _offerListingId;
@synthesize price = _price;
@synthesize salePrice = _salePrice;
@synthesize amountSaved = _amountSaved;
@synthesize percentageSaved = _percentageSaved;
@synthesize availability = _availability;
@synthesize availabilityAttributes = _availabilityAttributes;
@synthesize isEligibleForSuperSaverShipping = _isEligibleForSuperSaverShipping;
@synthesize isEligibleForPrime = _isEligibleForPrime;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"OfferListing" nsUri:@"http://webservices.amazon.com/AWSECommerceService/2011-08-01"];
   // [cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"OfferListingId" propertyName:@"offerListingId" type:PICO_TYPE_STRING clazz:nil];
    map[@"offerListingId"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Price" propertyName:@"price" type:PICO_TYPE_OBJECT clazz:[Price class]];
    map[@"price"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SalePrice" propertyName:@"salePrice" type:PICO_TYPE_OBJECT clazz:[Price class]];
    map[@"salePrice"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"AmountSaved" propertyName:@"amountSaved" type:PICO_TYPE_OBJECT clazz:[Price class]];
    map[@"amountSaved"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"PercentageSaved" propertyName:@"percentageSaved" type:PICO_TYPE_LONG clazz:nil];
    map[@"percentageSaved"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Availability" propertyName:@"availability" type:PICO_TYPE_STRING clazz:nil];
    map[@"availability"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"AvailabilityAttributes" propertyName:@"availabilityAttributes" type:PICO_TYPE_OBJECT clazz:[AvailabilityAttributes class]];
    map[@"availabilityAttributes"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IsEligibleForSuperSaverShipping" propertyName:@"isEligibleForSuperSaverShipping" type:PICO_TYPE_BOOL clazz:nil];
    map[@"isEligibleForSuperSaverShipping"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IsEligibleForPrime" propertyName:@"isEligibleForPrime" type:PICO_TYPE_BOOL clazz:nil];
    map[@"isEligibleForPrime"] = ps;
    
    return map;
}




@end
