// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "SimilarViewedProducts.h"
#import "SimilarViewedProduct.h"

@implementation SimilarViewedProducts

@synthesize similarViewedProduct = _similarViewedProduct;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"SimilarViewedProducts" nsUri:@"http://webservices.amazon.com/AWSECommerceService/2011-08-01"];
    //[cs autorelease];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"SimilarViewedProduct" propertyName:@"similarViewedProduct" type:PICO_TYPE_OBJECT clazz:[SimilarViewedProduct class]];
    map[@"similarViewedProduct"] = ps;
    
    return map;
}




@end
