// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "AvailabilityAttributes.h"

@implementation AvailabilityAttributes

@synthesize availabilityType = _availabilityType;
@synthesize isPreorder = _isPreorder;
@synthesize minimumHours = _minimumHours;
@synthesize maximumHours = _maximumHours;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [NSMutableDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"AvailabilityType" propertyName:@"availabilityType" type:PICO_TYPE_STRING clazz:nil];
    map[@"availabilityType"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IsPreorder" propertyName:@"isPreorder" type:PICO_TYPE_BOOL clazz:nil];
    map[@"isPreorder"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MinimumHours" propertyName:@"minimumHours" type:PICO_TYPE_LONG clazz:nil];
    map[@"minimumHours"] = ps;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MaximumHours" propertyName:@"maximumHours" type:PICO_TYPE_LONG clazz:nil];
    map[@"maximumHours"] = ps;
    
    return map;
}




@end
